# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김영재
title: 백엔드 서버 엔지니어
email: newy12@naver.com
website: https://newy12.github.io


# Dark Mode (true/false/never)
darkmode: never

# Social links
instagram_username: whatthepub_
github_username:  newy12
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: people/%EA%B9%80%EC%98%81%EC%9E%AC/100005892694461/
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-blog
  url: https://yjkim-dev.tistory.com/
# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/youngjae.jpeg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 기반의 3년차 서버 백엔드 개발자로 현재 케이블 방송을 통해 <mark>3,400만 가구</mark> 에 증권 경제 콘텐츠 제공, <mark>100.2만명</mark> 의 유튜브 구독자 수를 보유하고 있는 <mark>머니투데이방송</mark> 에서 백엔드 신규 플랫폼 개발 및 기존 서비스 리뉴얼 등을 해왔습니다.

  서비스에 대해 개발자 입장이 아닌 사용자 입장에서 먼저 생각하는 습관을 가지고 있으며, 항상 제 자신에게 의심을 품어, 여러 번 체크하는 버릇이 있어 Junit, Mockito 를 활용하여 수차례의 <mark>테스트코드</mark> 작성을 해오고 있습니다. 
  또한 꾸준한 개발 블로그 업로드를 하여 몰랐었던 지식을 기록해오고 있습니다.

  더 나은 서비스를 위해 과감한 리펙토링도 마다하지 않으며, 항상 효율적인 코드를 짜기 위해 코드 한 줄 한 줄 깊게 생각하는 편입니다. 

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 머니투데이방송
        link: https://mtn.co.kr/
        # link_text: boringcompany.com
        sub_title: Backend Engineer
        caption: 2022.09 - 현재
        quote: >
          3,400만 가구, 100.2만명의 유튜브 구독자 보유
        description: | # this will include new lines to allow paragraphs
            - 대규모 트래픽, 데이터 환경에서의 API/Batch 개발
            - [메인페이지](https://mtn.co.kr/), [뉴스페이지](https://news.mtn.co.kr/) 개발 및 트래픽 개선
            - 회원 관련 모든 배치프로그램 개발
            - Mybatis → JPA 마이그레이션 및 운영 관리
            - 인프라 NCP 환경에서의 개발 및 관리
      - layout: left
        title: 세이프소프트
        # link_text: boringcompany.com
        sub_title: Full Stack Engineer
        caption: 2021.03 - 2022.08
        quote: >

        description: | # this will include new lines to allow paragraphs
            - [중앙대학교 광명병원 임상시험센터 대상자 관리 시스템 프로젝트 참여](http://www.huscience.net/ko/smartTC/cau-gh.php)
            - 신규 서비스 전체 아키텍처 및 도메인 모델 설계
            - Thymeleaf 템플릿 엔진 활용한 SSR 구축
            - 내부 서비스 6개 시스템 유지보수 및 추가 개발 담당
            - IDC 인프라 환경에서의 개발 및 관리


  - title: 역량
    layout: text
    content: | # this will include new lines to allow paragraphs    
      <p style="font-size:27px;text-align:center;font-weight:bold;color:grey;">시스템 개발 및 유지보수</p>
      <br>
      <br>
      - 머니투데이방송 뉴스페이지, 메인페이지 유지보수 및 개발을 담당하였습니다. (2022. 10 ~ ing)
      - 머니투데이방송 Postfix 활용한 회원 관련 이벤트 처리 및 알림 배치 프로그램을 개발하였습니다. (2023.04 ~ 2023.05)
      - 머니투데이방송 회원정보 및 대량의 결제 데이터 이관 배치 프로그램을 개발하였습니다. (2022.12 ~ 2022.12)
      - 머니투데이방송 기존로그인 → SSO 전환 작업 및 SNS(Kakao,Naver) 로그인 개발을 하였습니다. (2022.10 ~ 2023.01)
      - 세이프소프트 중앙대광명병원 임상시험센터 대상자 관리 시스템 프로젝트 참여하여 대상자의 서명동의 및 사용자 인증 파트를 개발하였습니다. (2022.01 ~ 2022.07)
      - 세이프소프트 회사 소개 페이지 퍼블리싱 및 프론트 개발을 하였습니다. (2021.05 ~ 2021.07)
      - 세이프소프트 내부 서비스 6개 파이프라인 CI/CD 자동화를 구축하였습니다. (2021.10 ~ 2021.10)
      - 세이프소프트 사내 Bug Tracking System 프로젝트 개발에 참여하였습니다. (2021.08 ~ 2021.12)
      <br>
      <br>
      <p style="font-size:27px;text-align:center;font-weight:bold;color:grey;">시스템 리팩토링 및 마이그레이션</p>
      <br>
      <br>
      - 머니투데이방송 Postfix -> Cloud Outbound Mailer로의 이전 및 통합을 통해 NCP 클라우드 기반 메일링 시스템을 최적화하였습니다. (2023.11 ~ 2023.11)
      - 머니투데이방송 대량의 이메일 전송 시 메세지 손실 방지를 위해 메세지 큐를 탑재하였습니다. (2023.10 ~ 2023.10)
      - 머니투데이방송 10초마다 파일 추적 후 이벤트 처리하던 크론탭 → Java 와치서비스 적용 후 리소스 낭비를 개선하였습니다. (2023.09 ~ 2023.10)
      - 머니투데이방송 대량의 기사 데이터를 한번에 불러와 느려졌던 이슈를 페이징 및 캐싱하여 성능을 개선하였습니다. (2023.07 ~ 2023.08)
      - 머니투데이방송 기사 데이터 조회 시 조금 더 성능 최적화를 위해 Logstash 수집 인덱스에 칼럼 추가하여 성능을 개선하였습니다. (2023.01 ~ 2023.01)
      - 머니투데이방송 내부 서비스 70% PHP → Java 시스템 마이그레이션하였습니다. (2022.10 ~ 2022.12)
      - 머니투데이방송 내부 서비스 90% Mybatis → JPA 시스템 마이그레이션하였습니다. (2022.09 ~ 2022.11)
      - 세이프소프트 모든 웹사이트에 SSL 인증서를 적용하여 보안을 강화하였습니다. (2021.10 ~ 2021.10)
      - 세이프소프트 문서로 정리하던 API 명세 → Swagger OpenAPI로 전환하여 소통의 효율을 높였습니다. (2021.10 ~ 2021.10)
      <br>
      <br>
      <p style="font-size:27px;text-align:center;font-weight:bold;color:grey;">웹 어플리케이션 구현 & 배포 경험</p>
      <br>
      <br>
      - AWS Cloud에서 EC2 instance를 활용하여 프로젝트 서버를 구성하였습니다.
      - Nginx를 이용하여 트래픽 분산을 위한 서버 [로드 밸런싱](https://yjkim-dev.tistory.com/83)을 구축하였습니다. 
      - Jenkins를 활용하여 [파이프라인 CI/CD]([파이프라인 CI/CD (1)](https://yjkim-dev.tistory.com/11))를 구축하여 배포 자동화을 구현하였습니다.
      - Docker-compose를 활용한 [다중 컨테이너](https://yjkim-dev.tistory.com/76) 관리 및 프로세스 구축해 본적이 있습니다.
      <br>
      <br>
      <p style="font-size:27px;text-align:center;font-weight:bold;color:grey;">회고 및 발표</p>
      <br>
      <br>
      - [팀원들에게 도움이 되고자 Docker 사용법 및 컨테이너 관리 프로세스 설명](https://young-dev.notion.site/c17c4677efaf4f4780ef6cd41fed0648?pvs=4) (2023.05)
      - [MVC 패턴에 대한 기초적인 설명과 API 통신의 흐름에 대한 프로세스 설명](https://young-dev.notion.site/MVC-0329b3c8cb4644c582eb8749c738dd86) (2023.02)
      - [데이터량에 따른 MongoDB 성능 지표 확인](https://young-dev.notion.site/MongoDB-b6ff4a1839e04ecbb5b3b19ee3eea389) (2022.06)
      - [사내 MongoDB 도입을 위한 MongoDB에 대한 성능의 이점 및 실제 기업들의 활용방안 발표](https://young-dev.notion.site/MongoDB-43f94d1656714bcaa26970b4f82405ef) (2022.01)
      - [기초 프론트 개발에 필요한 전반적인 지식 및 템플릿 엔진에 대한 설명 발표](https://young-dev.notion.site/Box-Model-58fb86c3e7034b37bd0aa59a13c63679) (2021.10)
      <br>
      <br>
       <p style="font-size:27px;text-align:center;font-weight:bold;color:grey;">개인 블로그 활동</p>
      <br>
      <br>
      - 큰 부분에서부터 작은 부분까지 학습한 혹은 알게된 내용을 기록하고 내 것으로 소화하기 위해 꾸준히 [블로그](https://yjkim-dev.tistory.com/) 글 작성을 해오고 있습니다. 
      - 대부분 개발 관련 내용만 꾸준히 기술하였습니다.
      <br>
      <br>
       <p style="font-size:27px;text-align:center;font-weight:bold;color:grey;">코딩 관련 IT 서적 검토</p>
      <br>
      <br>
      - [수학이쑥쑥!코딩이척척! 초등코딩수학사고력 1~4단계 중 3단계](http://www.yes24.com/Product/Goods/101780376) 출간 전 검토자로 참여하였습니다.
      - 67p 순차탐색 그림 오류 / 68p 비행기 로봇의 미로 탈출을 위한 최단거리 답안 오류 / 75p 동물분류 알고리즘 그림 오류 검토 등 출간 전 검토하여 답안 오류를 제기하였습니다.
      - 책의 앞부분에 검토자 이름으로 표기되었습니다.
      <br>
      <br>
  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        quote: 
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - Java
          - Spring Boot, Spring MVC, Spring Batch, Spring Security
          - Spring Data JPA/Redis, QueryDSL, JWT, RabbitMQ
          - Junit, Mockito
      - layout: left
        title: DevOps
        quote: 
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - ELK
          - MySQL(MariaDB), MongoDB
          - Jenkins, Docker, Docker-compose
          - AWS(RDS/EC2/S3), NCP
          - Nginx, Tomcat
          - Swagger, Slack, Obsidian
      - layout: left
        title: Frontend
        quote: 
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - Javascript
          - React.js

  - title: Project # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  Movie Project
        caption: 2023.04 ~ 2023.05
        quote: >
          영화 커뮤니케이션 웹사이트
        description: | # this will include new lines to allow paragraphs
          - 영화를 좋아하는 사람들에게 영화의 개봉일자, 평점 등 정보를 제공하며 해당 영화에 댓글을 달아 사람들과 소통을 할 수 있는 프로젝트 입니다.
          - Springboot(Java), Spring security, JWT, Redis, Spring Data MongoDB, MongoDB, AWS(EC2) 
          - [영화 커뮤니케이션 웹사이트 포트폴리오 설명](https://young-dev.notion.site/API-818d769c5b014ceaa6191c24659a6be6)    
          - [영화 커뮤니케이션 웹사이트 깃허브 소스코드](https://github.com/MovieApplication/backend)
      - layout: left
        title: Summar Application
        caption: 2022.11 - 2023.03
        quote: >
          포트폴리오 소셜 어플리케이션
        description: | # this will include new lines to allow paragraphs
          - 대학생 혹은 직장인들을 타켓으로 잡아 그들의 커리어를 위한 포트폴리오 제작 플랫폼 서비스 어플리케이션 입니다.
          - Springboot(Java), Spring Data Jpa, Spring security, JWT, Redis, Mysql, AWS(EC2,RDS,S3)
          - [포트폴리오 소셜 어플리케이션 포트폴리오 설명](https://young-dev.notion.site/SUMMAR-API-7ca3cd4f333b49ca849c929e50460544)
          - [포트폴리오 소셜 어플리케이션 깃허브 소스코드](https://github.com/ios-summar/Backend)
          - <p><s>App Store 배포</s> (현재 앱스토어에서 내린 상태)</p>
      - layout: left
        title:  Freelancer Market Project
        caption: 2020.12 - 2021.01
        quote: >
          프리랜서 마켓 서비스(KH정보교육원 교육당시 최종 프로젝트 7조 중 1등)
        description: | # this will include new lines to allow paragraphs
          - 크몽이나, 숨고같은 프리랜서들을 위한 프리랜서 마켓 서비스 웹사이트 입니다.
          - Spring(Java), Mybatis, Oracle, AWS(EC2,RDS,S3)
          - [프리랜서 마켓 서비스 웹사이트 포트폴리오 설명](https://young-dev.notion.site/KH-a3881a368d1d4e8ab59b1fcfd0d63da5)
          - [프리랜서 마켓 서비스 웹사이트 깃허브 소스코드](https://github.com/newy12/Final_19oclockProject)
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  KH 정보교육원
        caption: 2020.08 ~ 2021.01
        description: | # this will include new lines to allow paragraphs
          - 웹 개발에 관심이 생김과 동시에 웹 어플리케이션 교육의 필요성을 느껴 참여하였습니다.
          - 프론트에 필요한 기본 언어 교육과 Spring을 이용한 서버 구축 및 풀스택 과정을 배웠습니다.
      - layout: left
        title:  이지디자인컴퓨터학원
        caption: 2019.04 ~ 2019.09
        description: | # this will include new lines to allow paragraphs
          - 처음 웹에 대해 접하면서 화면 구상에 대한 궁금증을 해결하기 위해 참여하였습니다.
          - HTML, CSS, JS 등 화면 구성에 필요한 언어에 대한 깊이 있는 교육 수강을 하였습니다.
          - 기존 웹사이트를 클론코딩하여 퍼블리싱에 대한 공부를 하였고 퍼블리싱 기술을 습득 하였습니다.
      - layout: left
        title:  청주대학교
        caption: 2015.03 ~ 2021.02
        description: | # this will include new lines to allow paragraphs
          - 컴퓨터정보공학과 부 학생회장 활동을 하여 리더십, 협동심, 문제해결능력 등 다양한 역량을 키울수 있는 소중한 기회를 얻었습니다.
          - 학과 내에서의 대표적인 프로젝트나 행사를 성공적으로 기획하고 진행함으로써 학우들 간의 유대감을 증진 시키는데 기여하였습니다. 
          - Java, C, Python, Database 등 기초 개발언어에 대한 교육을 수료하였습니다.
  - title: Certificate # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  정보처리기사
        caption: 
        description: | # this will include new lines to allow paragraphs
          - 2021.06 취득 
          - 한국산업인력 공단
    
          
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
