# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김영재
title: 백엔드 서버 엔지니어
email: newy12@naver.com
website: https://newy12.github.io


# Dark Mode (true/false/never)
darkmode: never

# Social links
instagram_username: whatthepub_
github_username:  newy12
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: people/%EA%B9%80%EC%98%81%EC%9E%AC/100005892694461/
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-blog
  url: https://yjkim-dev.tistory.com/
# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/youngjae.jpeg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring, AWS 기반의 3년차 서버 백엔드 개발자로 현재 케이블 방송을 통해 <mark>3,400만 가구</mark> 에 증권 경제 콘텐츠 제공, <mark>100.2만명</mark> 의 유튜브 구독자 수를 보유하고 있는 <mark>머니투데이방송</mark> 에서 백엔드 신규 플랫폼 개발 및 기존 서비스 리뉴얼 등을 해왔습니다.

  서비스에 대해 개발자 입장이 아닌 사용자 입장에서 먼저 생각하는 습관을 가지고 있으며, 항상 제 자신에게 의심을 품어, 여러 번 체크하는 버릇이 있어 Junit, Mockito 를 활용하여 수차례의 <mark>테스트코드</mark> 작성을 해오고 있습니다. 
  또한 꾸준한 개발 블로그 업로드를 하여 몰랐었던 지식을 기록해오고 있습니다.

  더 나은 서비스를 위해 과감한 리펙토링도 마다하지 않으며, 항상 효율적인 코드를 짜기 위해 코드 한 줄 한 줄 깊게 생각하는 편입니다. 
content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 머니투데이방송
        link: https://mtn.co.kr/
        # link_text: boringcompany.com
        sub_title: Backend Engineer
        caption: 2022.09 - 현재
        quote: >
          3,400만 가구, 100.2만명의 유튜브 구독자 보유
        description: | # this will include new lines to allow paragraphs
            - 대규모 트래픽, 데이터 환경에서의 API/Batch 개발
            - MTN 메인페이지 , 뉴스 메인페이지 개발 및 트래픽 개선
            - Mybatis → JPA 마이그레이션 및 운영 관리
            - 인프라 AWS 환경에서의 개발 및 관리
      - layout: left
        title: 세이프소프트
        link: http://safesoft.co.kr/
        # link_text: boringcompany.com
        sub_title: Full Stack Engineer
        caption: 2021.03 - 2022.08
        quote: >

        description: | # this will include new lines to allow paragraphs
            - [중앙대학교병원 임상시험센터 대상자 관리 시스템 프로젝트 참여](https://gh.cauhs.or.kr/home/conts/105021001000000.do)
            - 신규 서비스 전체 아키텍처 및 도메인 모델 설계
            - Thymeleaf 템플릿 엔진 활용한 SSR 구축
            - 사내 메인 프로젝트 6개 추가 개발 및 유지보수 관리 담당
            - IDC 인프라 환경에서의 개발 및 관리


  - title: 역량
    layout: text
    content: | # this will include new lines to allow paragraphs    
      <p style="font-size:27px;text-align:center;font-weight:bold;color:grey;">시스템 개발 및 유지보수</p>
      <br>
      <br>
      - 머니투데이방송 뉴스페이지, 메인페이지 유지보수 담당 (2023. 10 ~  )
      - 사내 메일서버 구축 후 각종 이벤트 (휴면전환 처리, 개인정보수집 안내 등..)에 따른 메일 전송 개발(2023.04 ~ 2023.05)
      - 회원정보 및 결제 데이터 이관 배치프로그램 개발 (2022.12 ~ 2022.12)
      - 머니투데이방송 통합로그인 전환 SSO 개발 참여 (2022.10 ~ 2023.01)
      - 광명 중앙대학교병원 임상시험센터 대상자 관리 자동화 시스템 프로젝트 개발 참여 (2022.01 ~ 2022.07)
      - 세이프소프트 메인 홈페이지 퍼블리싱 및 프론트 개발 (2021.05 ~ 2021.07)
      - 세이프소프트 사내 6개의 시스템 배포 자동화 구축 (2021.10 ~ 2021.10)
      - 세이프소프트 사내 Bug Tracking System 개발 참여 (2021.08 ~ 2021.12)
      <br>
      <br>
      <p style="font-size:27px;text-align:center;font-weight:bold;color:grey;">시스템 리팩토링 및 마이그레이션</p>
      <br>
      <br>
      - 머니투데이방송 기사 리스트 목록 조회 쿼리 개선 후 속도 개선(paging + 캐시 추가) (2023.07 ~ 2023.08) 
      - 머니투데이방송 정산시스템 약간의 오차로 인한 결제 정산 쿼리 개선 (2023.01 ~ 2023.01)
      - 머니투데이방송 뉴스페이지에  Logstash 기사 수집인덱스 쿼리 개선 (2023.01 ~ 2023.01)
      - 머니투데이방송 CMS시스템 PHP → JAVA 시스템 마이그레이션 (2022.10 ~ 2022.12)
      - 머니투데이방송 메인페이지 JPA 마이그레이션 (2022.09 ~ 2022.11)
      - 머니투데이방송 뉴스 페이지 일부 JPA 마이그레이션 (2022.09 ~ 2022.11)
      - 세이프소프트 메인 페이지 제외한 프로젝트 전부 SSL 인증서로 마이그레이션 (2021.10 ~ 2021.10)
      - 세이프소프트 프로젝트 전부 Google Sheets → Swagger OpenAPI 마이그레이션 (2021.10 ~ 2021.10)
      <br>
      <br>
      <p style="font-size:27px;text-align:center;font-weight:bold;color:grey;">빌드 및 배포 자동화</p>
      <br>
      <br>
      - 매번 지루하게 반복되는 배포 절차가 귀찮아서 Jenkins 및 GitHook 이용하여 배포자동화 개발
      - 커밋 하나로 기존에 돌고있는 서비스 포트 종료 후 새로 빌드된 파일 해당 서버에 할당 및 포트 생성
      - 배포 자동화를 위한 groovy 스크립트 작성 및 블로그 정리
      - 빌드 정상 처리 분기 확인 후 Discord 및 Slack 에 알림 서비스 연동 및 개발
      - Docker를  이용할 사람들을 위해 외부에서도 로컬 접속 가능하도록 Ngrok 블로그 정리  및 연동
      - 사람들이 보고 쉽게 따라 할수 있도록 블로그 정리
      - [배포자동화 따라하기 (1)](https://yjkim-dev.tistory.com/11)
      - [배포자동화 따라하기 (2)](https://yjkim-dev.tistory.com/12)
      - [배포자동화 따라하기 (3)](https://yjkim-dev.tistory.com/13)
      - [배포자동화 따라하기 (4)](https://yjkim-dev.tistory.com/14)
      - [배포자동화 따라하기 (5)](https://yjkim-dev.tistory.com/15)                    
      <p style="font-size:27px;text-align:center;font-weight:bold;color:grey;">사내 세미나 발표</p>
      <br>
      <br>
      - [Docker 개념 및 Docker Compose 사용](https://young-dev.notion.site/c17c4677efaf4f4780ef6cd41fed0648?pvs=4) (2023.05)
      - [MVC Pattern 및 웹 통신 프로토콜](https://young-dev.notion.site/MVC-0329b3c8cb4644c582eb8749c738dd86) (2023.02)
      - [데이터량에 따른 MongoDB 성능 비교](https://young-dev.notion.site/MongoDB-b6ff4a1839e04ecbb5b3b19ee3eea389) (2022.06)
      - [MongoDB 주요 기능 & 활용 방안](https://young-dev.notion.site/MongoDB-43f94d1656714bcaa26970b4f82405ef) (2022.01)
      - [Box Model 및 템플릿 엔진](https://young-dev.notion.site/Box-Model-58fb86c3e7034b37bd0aa59a13c63679) (2021.10)
      <br>
      <br>
       <p style="font-size:27px;text-align:center;font-weight:bold;color:grey;">코딩 관련 IT 서적 검토</p>
      <br>
      <br>
      - [수학이쑥쑥!코딩이척척! 초등코딩수학사고력 3단계](http://www.yes24.com/Product/Goods/101780376) 출간 전 검토
      - 75p 순차탐색 그림 오류 검토 및 수정 
      - 68p 비행기 로봇의 미로 탈출을 위한 최단거리 답안 오류 검토 및 수정
      - 67p 동물분류 알고리즘 그림 오류 검토 및 수정
      <br>
      <br>
  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        quote: 
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - Java ,  Node.js(express.js + sequelize)
          - Spring Boot, Spring MVC, Spring Batch, Spring Security, 
          - Spring Data JPA/Redis, JWT
          - Junit4/5, (BDD)Mockito
          - Gradle, Maven
          - JetbrainTool(IntelliJ, WebStorm, DataGrip), Visual Studio Code
      - layout: left
        title: DevOps
        quote: 
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - ELK(Elastic Search, Logstash, Kibana)
          - MySQL, MariaDB, MSSQL, MongoDB
          - Jenkins, Docker
          - AWS RDS/EC2/S3 Bucket
          - Nginx, Tomcat
          - Atlassian jira/Confluence, Swagger, Slack 
      - layout: left
        title: Frontend
        quote: 
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - ES6, React.js, Flutter
          - Npm, Webpack  

  - title: Project # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  Movie Project
        caption: 2023.04 ~ 2023.05
        quote: >
          영화 커뮤니케이션 웹사이트
        description: | # this will include new lines to allow paragraphs
          - [Movie Project Portfolio](https://young-dev.notion.site/API-818d769c5b014ceaa6191c24659a6be6)    
          - [github URL](https://github.com/MovieApplication/backend)
      - layout: left
        title: Summar Application
        caption: 2022.11 - 2023.03
        quote: >
          포트폴리오 소셜 어플리케이션 입니다.
        description: | # this will include new lines to allow paragraphs
          - [SUMMAR Application Portfolio](https://young-dev.notion.site/SUMMAR-API-7ca3cd4f333b49ca849c929e50460544)
          - <p><s>App Store 배포</s> (현재 앱스토어에서 내린상태)</p>
          - [github URL](https://github.com/ios-summar/Backend)
      - layout: left
        title:  Freelancer Market Project
        caption: 2020.12 - 2021.01
        quote: >
          국비지원 파이널 프로젝트 7조 중 1위한 작품입니다.
        description: | # this will include new lines to allow paragraphs
          - [Freelancer Market Portfolio](https://young-dev.notion.site/KH-a3881a368d1d4e8ab59b1fcfd0d63da5)
          - [github URL](https://github.com/newy12/Final_19oclockProject)
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  KH 정보교육원
        caption: 2020.08 ~ 2021.01
        description: | # this will include new lines to allow paragraphs
          - 웹 개발에 관심이 생김과 동시에 웹 어플리케이션 교육의 필요성을 느껴 참여
          - 프론트에 필요한 기본 언어 교육과 Spring을 이용한 서버 구축 및 풀스텍 과정
      - layout: left
        title:  이지디자인컴퓨터학원
        caption: 2019.04 ~ 2019.09
        description: | # this will include new lines to allow paragraphs
          - 처음 웹에 대해 접하면서 화면 구상에 대한 궁금증을 해결하기 위해 참여
          - HTML, CSS, JS 등 화면 구성에 필요한 언어에 대한 깊이 있는 교육 수강
          - 기존 웹사이트 클론코딩 및 기술 습득          
      - layout: left
        title:  청주대학교
        caption: 2015.03 ~ 2021.02 (학사 졸업)
        description: | # this will include new lines to allow paragraphs
          - 컴퓨터정보공학과 부 학생회장
          - Java, C, database, Python 등 기초 개발언어에 대한 교육
  - title: Certificate # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  정보처리기사
        caption: 
        description: | # this will include new lines to allow paragraphs
          - 2021.06 취득 
          - 한국산업인력 공단
    
          
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
